version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/byte_builder/

hooks:
  BeforeInstall:
    - location: scripts/set-env.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/set-permissions.sh
      timeout: 300
      runas: ubuntu